### PR TITLE
Updated link to the GS guide

### PR DESCRIPTION
**Pull request by emannenicholas**

### CODE REVIEW

**Comment by jnation3406** [comment]
This is great, but the whole point of having a "latest" file to link to is so we don't have to do this each time its updated! Is it possible to store the file in a fixed place and update it when it changes, rather than add a new file to the server and have to update this link? I think theres probably some other places we link to the "latest" file that are broken too...

**Comment by emannenicholas** [comment]
I agree that we should handle the latest file better, but I'm not really sure how to do that.  I fixed all of the instances of the old link I could find as a quick fix.  Is there any way you have time next week to help @nvolgenau and I figure out a better solution (provided Nikolaus has time)?

**Comment by jnation3406** [comment]
> I agree that we should handle the latest file better, but I'm not really sure how to do that. I fixed all of the instances of the old link I could find as a quick fix. Is there any way you have time next week to help @nvolgenau and I figure out a better solution (provided Nikolaus has time)?

Sure, I'm not actually sure how our website hosting is set up so let me look into it a bit and get back to you. My hope is there is a way for you to upload a file over an existing one, preserving its same link, so we could just use that link as the latest document and update the file there when needed...

**Comment by jnation3406** [comment]
> I agree that we should handle the latest file better, but I'm not really sure how to do that. I fixed all of the instances of the old link I could find as a quick fix. Is there any way you have time next week to help @nvolgenau and I figure out a better solution (provided Nikolaus has time)?

@emannenicholas and @nvolgenau - If you look at the edit document section of [this page](https://guide.wagtail.org/en-latest/how-to-guides/manage-documents/) you should see the way to update an existing document instead of adding a new one. This should work to just update the file but keep the link to it the same assuming it has the same exact filename. But unfortunately, it was broken in the version of wagtail we currently use (4.0.2) - it was fixed in wagtail 4.2+  I think so if we update our main page this should become a viable option. I guess until then we will have to always replace the links everywhere we use them whenever we update the file.

**Pull request merged**
